# Generated by Django 2.2.3 on 2019-07-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korgi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
